config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :tickets
  resources :funcions
  resources :salas
  resources :trabajadors
  resources :pais_origens
  resources :cines
  resources :est_ticks
  resources :est_funs
  resources :horarios
  resources :tipo_tickets
  resources :tipo_salas
  resources :cargos
  resources :edads
  resources :peliculas
  resources :generos
  resources :pruebas

  get 'page/index'
  get 'page/vista'
  get 'page/procedimiento'
  get 'page/auditor'
  get 'page/mtb'
  get 'pages/index'
  get 'pages/vista'
  get 'pages/procedimiento'
  get 'pages/auditor'
  get 'pages/mtb'

  root 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :trabajador, :foreign_key => :admin_id, :primary_key => :trabajador_rut
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auditor.rb
class Auditor < ApplicationRecord
  self.table_name = "audit_tables"
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  #self.primary_key = :car_id
  has_many :trabajador, :foreign_key => :tra_car, :primary_key => :car_id

  validates :car_id , uniqueness: true
end

app/models/cine.rb
class Cine < ApplicationRecord
  has_many :trabajador, :foreign_key => :tra_cine, :primary_key => :cine_id
  has_many :sala, :foreign_key => :sala_cine, :primary_key => :cine_id

  validates :cine_id , uniqueness: true
end

app/models/edad.rb
class Edad < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_ed, :primary_key => :ed_id

  validates :ed_id , uniqueness: true
end

app/models/est_fun.rb
class EstFun < ApplicationRecord
  has_many :funcion, :foreign_key => :fun_ef, :primary_key => :ef_id

  validates :ef_id , uniqueness: true
end

app/models/est_tick.rb
class EstTick < ApplicationRecord
  has_many :ticket, :foreign_key => :tick_et, :primary_key => :et_id

  validates :et_id , uniqueness: true
end

app/models/funcion.rb
class Funcion < ApplicationRecord
  belongs_to :sala, :foreign_key => :fun_sala, :primary_key => :sala_id
  belongs_to :est_fun, :foreign_key => :fun_ef, :primary_key => :ef_id
  belongs_to :pelicula, :foreign_key => :fun_peli, :primary_key => :peli_id
  belongs_to :horario, :foreign_key => :fun_hor, :primary_key => :hor_id
  has_many :ticket, :foreign_key => :tick_fun, :primary_key => :fun_id

  validates :fun_id , uniqueness: true
end

app/models/genero.rb
class Genero < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_gen, :primary_key => :gen_id

  validates :gen_id , uniqueness: true
end

app/models/horario.rb
class Horario < ApplicationRecord
  has_many :funcion, :foreign_key => :fun_hor, :primary_key => :hor_id

  validates :hor_id , uniqueness: true
end

app/models/pais_origen.rb
class PaisOrigen < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_po, :primary_key => :po_id

  validates :po_id , uniqueness: true
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
  belongs_to :edad, :foreign_key => :peli_ed, :primary_key => :ed_id
  belongs_to :genero, :foreign_key => :peli_gen, :primary_key => :gen_id
  belongs_to :pais_origen, :foreign_key => :peli_po, :primary_key => :po_id
  has_many :funcion, :foreign_key => :fun_peli, :primary_key => :peli_id

  validates :peli_id , uniqueness: true
end

app/models/prueba.rb
class Prueba < ApplicationRecord
end

app/models/sala.rb
class Sala < ApplicationRecord
  belongs_to :tipo_sala, :foreign_key => :sala_ts, :primary_key => :ts_id
  belongs_to :cine, :foreign_key => :sala_cine, :primary_key => :cine_id
  has_many :funcion, :foreign_key => :fun_sala, :primary_key => :sala_id

  validates :sala_id , uniqueness: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :tipo_ticket, :foreign_key => :tick_tt, :primary_key => :tt_id
  belongs_to :funcion, :foreign_key => :tick_fun, :primary_key => :fun_id
  belongs_to :est_tick, :foreign_key => :tick_et, :primary_key => :et_id

  validates :tick_id , uniqueness: true
end

app/models/tipo_sala.rb
class TipoSala < ApplicationRecord
  has_many :sala, :foreign_key => :sala_ts, :primary_key => :ts_id

  validates :ts_id , uniqueness: true
end

app/models/tipo_ticket.rb
class TipoTicket < ApplicationRecord
  has_many :ticket, :foreign_key => :tick_tt, :primary_key => :tt_id

  validates :tt_id , uniqueness: true
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :cargo, :foreign_key => :tra_car, :primary_key => :car_id
  belongs_to :cine, :foreign_key => :tra_cine, :primary_key => :cine_id

  has_one :admin, :foreign_key => :admin_id, :primary_key => :trabajador_rut

  validates :tra_id , uniqueness: true
end

app/models/v_tick_peli.rb
class VTickPeli < ApplicationRecord
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  # GET /cargos
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  def create
    @cargo = Cargo.new(cargo_params)

    if @cargo.save
      redirect_to @cargo, notice: 'Cargo ha sido agregado exitosamente.'
    else
      redirect_to page_mtb_path, notice: 'Cargo no se pudo agregar.'
    end
  end

  # PATCH/PUT /cargos/1
  def update
    if @cargo.update(cargo_params)
      redirect_to @cargo, notice: 'Cargo ha sido actualizado.'
    else
      redirect_to page_mtb_path, notice: 'Cargo no se pudo actualizar.'
    end
  end

  # DELETE /cargos/1
  def destroy
    @cargo.destroy
    redirect_to page_mtb_path, notice: 'Cargo ha sido eliminado.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cargo_params
      params.require(:cargo).permit(:car_id, :car_desc)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/cines_helper.rb
module CinesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/cargos/_form.html.erb
<%= form_with(model: cargo, local: true, class: "form-horizontal") do |form| %>
  <% if cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% cargo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :car_id, "ID" , class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= form.text_field :car_id, id: :cargo_car_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :car_desc, "Descripcion" , class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= form.text_field :car_desc, id: :cargo_car_desc, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <div class="actions">
        <%= form.submit "Enviar", class: "btn btn-block btn-success "%>
      </div>
    </div>
  </div>
<% end %>

</form>

app/views/cargos/edit.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Editar Cargo</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form', cargo: @cargo %>

        <%= link_to '<i class="fa fa-backward"></i> Back'.html_safe, page_mtb_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargos</h1>

<table>
  <thead>
    <tr>
      <th>Car desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.car_desc %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo', new_cargo_path %>

app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Detalles Cargo</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <dl class="dl-horizontal">
          <dt>ID</dt>
          <dd><%= @cargo.car_id %></dd>
          <dt>Descripcion</dt>
          <dd><%= @cargo.car_desc %></dd>
        </dl>
      </div>
    </div>
    <%= link_to '<i class="fa fa-pencil"></i> Editar'.html_safe, edit_cargo_path(@cargo), class: "btn btn-warning" %>
    <%= link_to '<i class="fa fa-backward"></i> Volver'.html_safe,page_mtb_path, class: "btn btn-primary" %>
  </div>
</div>