config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :tickets
  resources :funcions
  resources :salas
  resources :trabajadors
  resources :pais_origens
  resources :cines
  resources :est_ticks
  resources :est_funs
  resources :horarios
  resources :tipo_tickets
  resources :tipo_salas
  resources :cargos
  resources :edads
  resources :peliculas
  resources :generos
  resources :pruebas

  get 'page/index'
  get 'page/vista'
  get 'page/procedimiento'
  get 'page/auditor'
  get 'page/mtb'
  get 'pages/index'
  get 'pages/vista'
  get 'pages/procedimiento'
  get 'pages/auditor'
  get 'pages/mtb'

  root 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :trabajador, :foreign_key => :admin_id, :primary_key => :trabajador_rut
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auditor.rb
class Auditor < ApplicationRecord
  self.table_name = "audit_tables"
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  #self.primary_key = :car_id
  has_many :trabajador, :foreign_key => :tra_car, :primary_key => :car_id

  validates :car_id , uniqueness: true
end

app/models/cine.rb
class Cine < ApplicationRecord
  has_many :trabajador, :foreign_key => :tra_cine, :primary_key => :cine_id
  has_many :sala, :foreign_key => :sala_cine, :primary_key => :cine_id

  validates :cine_id , uniqueness: true
end

app/models/edad.rb
class Edad < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_ed, :primary_key => :ed_id

  validates :ed_id , uniqueness: true
end

app/models/est_fun.rb
class EstFun < ApplicationRecord
  has_many :funcion, :foreign_key => :fun_ef, :primary_key => :ef_id

  validates :ef_id , uniqueness: true
end

app/models/est_tick.rb
class EstTick < ApplicationRecord
  has_many :ticket, :foreign_key => :tick_et, :primary_key => :et_id

  validates :et_id , uniqueness: true
end

app/models/funcion.rb
class Funcion < ApplicationRecord
  belongs_to :sala, :foreign_key => :fun_sala, :primary_key => :sala_id
  belongs_to :est_fun, :foreign_key => :fun_ef, :primary_key => :ef_id
  belongs_to :pelicula, :foreign_key => :fun_peli, :primary_key => :peli_id
  belongs_to :horario, :foreign_key => :fun_hor, :primary_key => :hor_id
  has_many :ticket, :foreign_key => :tick_fun, :primary_key => :fun_id

  validates :fun_id , uniqueness: true
end

app/models/genero.rb
class Genero < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_gen, :primary_key => :gen_id

  validates :gen_id , uniqueness: true
end

app/models/horario.rb
class Horario < ApplicationRecord
  has_many :funcion, :foreign_key => :fun_hor, :primary_key => :hor_id

  validates :hor_id , uniqueness: true
end

app/models/pais_origen.rb
class PaisOrigen < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_po, :primary_key => :po_id

  validates :po_id , uniqueness: true
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
  belongs_to :edad, :foreign_key => :peli_ed, :primary_key => :ed_id
  belongs_to :genero, :foreign_key => :peli_gen, :primary_key => :gen_id
  belongs_to :pais_origen, :foreign_key => :peli_po, :primary_key => :po_id
  has_many :funcion, :foreign_key => :fun_peli, :primary_key => :peli_id

  validates :peli_id , uniqueness: true
end

app/models/prueba.rb
class Prueba < ApplicationRecord
end

app/models/sala.rb
class Sala < ApplicationRecord
  belongs_to :tipo_sala, :foreign_key => :sala_ts, :primary_key => :ts_id
  belongs_to :cine, :foreign_key => :sala_cine, :primary_key => :cine_id
  has_many :funcion, :foreign_key => :fun_sala, :primary_key => :sala_id

  validates :sala_id , uniqueness: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :tipo_ticket, :foreign_key => :tick_tt, :primary_key => :tt_id
  belongs_to :funcion, :foreign_key => :tick_fun, :primary_key => :fun_id
  belongs_to :est_tick, :foreign_key => :tick_et, :primary_key => :et_id

  validates :tick_id , uniqueness: true
end

app/models/tipo_sala.rb
class TipoSala < ApplicationRecord
  has_many :sala, :foreign_key => :sala_ts, :primary_key => :ts_id

  validates :ts_id , uniqueness: true
end

app/models/tipo_ticket.rb
class TipoTicket < ApplicationRecord
  has_many :ticket, :foreign_key => :tick_tt, :primary_key => :tt_id

  validates :tt_id , uniqueness: true
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :cargo, :foreign_key => :tra_car, :primary_key => :car_id
  belongs_to :cine, :foreign_key => :tra_cine, :primary_key => :cine_id

  has_one :admin, :foreign_key => :admin_id, :primary_key => :trabajador_rut

  validates :tra_id , uniqueness: true
end

app/models/v_tick_peli.rb
class VTickPeli < ApplicationRecord
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/page/auditor.html.erb
<div class="row">
  <div class="col-lg-8">
      <h1 class="page-header">Auditoria</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="a">
          <thead>
            <tr>
              <th>Transaccion</th>
              <th>Tabla Auditada</th>
              <th>Fecha cambio</th>
              <th>Usuario</th>
              <th>Id tabla</th>
              <th>Dato nuevo</th>
              <th>Dato antiguo</th>
            </tr>
          </thead>
          <tbody>
            <% @audi.each do |a| %>
            <tr>
              <td><%= a.aud_trans %></td>
              <td><%= a.aud_table %></td>
              <td><%= a.aud_fecha %></td>
              <td><%= a.aud_user %></td>
              <td><%= a.aud_tabla_id %></td>
              <td><%= a.aud_nuevo %></td>
              <td><%= a.aud_antiguo %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('#a').DataTable();
  });
</script>

app/views/page/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Bienvenido</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-4 col-md-6 col-md-offset-2">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-users fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%= @trab %></div>
                <div>Trabajadores</div>
              </div>
            </div>
          </div>
          <a href="#">
            <div class="panel-footer">
              <span class="pull-left"><%= link_to 'Ver Detalles', trabajadors_path %></span>
              <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
              <div class="clearfix"></div>
            </div>
          </a>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="panel panel-green">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-ticket fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%= @tick %></div>
                <div>Tickets</div>
              </div>
            </div>
          </div>
          <a href="#">
            <div class="panel-footer">
                <span class="pull-left"><%= link_to 'Ver Detalles', tickets_path %></span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-4 col-md-6 col-md-offset-2">
        <div class="panel panel-yellow">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-video-camera fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%= @fun %></div>
                <div>Funciones</div>
              </div>
            </div>
          </div>
          <a href="#">
              <div class="panel-footer">
                <span class="pull-left"><%= link_to 'Ver Detalles', funcions_path %></span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
          </a>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="panel panel-red">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="fa fa-film fa-5x"></i>
              </div>
              <div class="col-xs-9 text-right">
                <div class="huge"><%= @pel %></div>
                <div>Peliculas</div>
              </div>
            </div>
          </div>
          <a href="#">
            <div class="panel-footer">
              <span class="pull-left"><%= link_to 'Ver Detalles', peliculas_path %></span>
              <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
              <div class="clearfix"></div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/page/procedimiento.html.erb
  <div class="row">
    <div class="col-lg-8">
        <h1 class="page-header">Estadistico</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <table width="100%" class="table table-striped table-bordered table-hover" id="p">
            <thead>
              <tr>
                <th>Cine</th>
                <th>Nombre</th>
                <th>Cant. cajeros</th>
                <th>Tickets vendidos</th>
                <th>Tickets devueltos</th>
                <th>Dias pri/ult venta</th>
                <th>Usuario</th>
                <th>IP</th>
                <th>Fecha Reporte</th>
              </tr>
            </thead>
            <tbody>
              <% @esta.each do |e| %>
              <tr>
                <td><%= e.rst_cine_id %></td>
                <td><%= e.rst_cine_nom %></td>
                <td><%= e.rst_cajeros %></td>
                <td><%= e.rst_vendidos %></td>
                <td><%= e.rst_dev %></td>
                <td><%= e.rst_dias %></td>
                <td><%= e.rst_usuario %></td>
                <td><%= e.rst_ip %></td>
                <td><%= e.rst_fecha %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('#p').DataTable();
  });
</script>

app/views/page/vista.html.erb
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Vistas</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body">

          <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="t1" >
                <h4 class="panel-title">
                  <a role="button" data-toggle="collapse" data-parent="#accordion" href="#c1" aria-expanded="true" aria-controls="c1">
                    Tickets vendidos por pelicula en estreno
                  </a>
                </h4>
              </div>
              <div id="c1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="t1">
                <div class="panel-body">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Ticket Vendidos</th>
                        <th>Pelicula Estrenada</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @vis1.each do |c| %>
                      <tr>
                        <td><%= c.ticketvendidos %></td>
                        <td><%= c.pelicula %></td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="t2">
                <h4 class="panel-title">
                  <a role="button" data-toggle="collapse" data-parent="#accordion" href="#c2" aria-expanded="true" aria-controls="c2">
                    Cant. Peliculas canceladas por horario
                  </a>
                </h4>
              </div>
              <div id="c2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="t2">
                <div class="panel-body">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Cant. Pelicula</th>
                        <th>Horario</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @vis2.each do |c| %>
                      <tr>
                        <td><%= c.pelican %></td>
                        <td><%= c.horario %></td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>