config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :tickets
  resources :funcions
  resources :salas
  resources :trabajadors
  resources :pais_origens
  resources :cines
  resources :est_ticks
  resources :est_funs
  resources :horarios
  resources :tipo_tickets
  resources :tipo_salas
  resources :cargos
  resources :edads
  resources :peliculas
  resources :generos
  resources :pruebas

  get 'page/index'
  get 'page/vista'
  get 'page/procedimiento'
  get 'page/auditor'
  get 'page/mtb'
  get 'pages/index'
  get 'pages/vista'
  get 'pages/procedimiento'
  get 'pages/auditor'
  get 'pages/mtb'

  root 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :trabajador, :foreign_key => :admin_id, :primary_key => :trabajador_rut
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auditor.rb
class Auditor < ApplicationRecord
  self.table_name = "audit_tables"
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  #self.primary_key = :car_id
  has_many :trabajador, :foreign_key => :tra_car, :primary_key => :car_id

  validates :car_id , uniqueness: true
end

app/models/cine.rb
class Cine < ApplicationRecord
  has_many :trabajador, :foreign_key => :tra_cine, :primary_key => :cine_id
  has_many :sala, :foreign_key => :sala_cine, :primary_key => :cine_id

  validates :cine_id , uniqueness: true
end

app/models/edad.rb
class Edad < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_ed, :primary_key => :ed_id

  validates :ed_id , uniqueness: true
end

app/models/est_fun.rb
class EstFun < ApplicationRecord
  has_many :funcion, :foreign_key => :fun_ef, :primary_key => :ef_id

  validates :ef_id , uniqueness: true
end

app/models/est_tick.rb
class EstTick < ApplicationRecord
  has_many :ticket, :foreign_key => :tick_et, :primary_key => :et_id

  validates :et_id , uniqueness: true
end

app/models/funcion.rb
class Funcion < ApplicationRecord
  belongs_to :sala, :foreign_key => :fun_sala, :primary_key => :sala_id
  belongs_to :est_fun, :foreign_key => :fun_ef, :primary_key => :ef_id
  belongs_to :pelicula, :foreign_key => :fun_peli, :primary_key => :peli_id
  belongs_to :horario, :foreign_key => :fun_hor, :primary_key => :hor_id
  has_many :ticket, :foreign_key => :tick_fun, :primary_key => :fun_id

  validates :fun_id , uniqueness: true
end

app/models/genero.rb
class Genero < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_gen, :primary_key => :gen_id

  validates :gen_id , uniqueness: true
end

app/models/horario.rb
class Horario < ApplicationRecord
  has_many :funcion, :foreign_key => :fun_hor, :primary_key => :hor_id

  validates :hor_id , uniqueness: true
end

app/models/pais_origen.rb
class PaisOrigen < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_po, :primary_key => :po_id

  validates :po_id , uniqueness: true
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
  belongs_to :edad, :foreign_key => :peli_ed, :primary_key => :ed_id
  belongs_to :genero, :foreign_key => :peli_gen, :primary_key => :gen_id
  belongs_to :pais_origen, :foreign_key => :peli_po, :primary_key => :po_id
  has_many :funcion, :foreign_key => :fun_peli, :primary_key => :peli_id

  validates :peli_id , uniqueness: true
end

app/models/prueba.rb
class Prueba < ApplicationRecord
end

app/models/sala.rb
class Sala < ApplicationRecord
  belongs_to :tipo_sala, :foreign_key => :sala_ts, :primary_key => :ts_id
  belongs_to :cine, :foreign_key => :sala_cine, :primary_key => :cine_id
  has_many :funcion, :foreign_key => :fun_sala, :primary_key => :sala_id

  validates :sala_id , uniqueness: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :tipo_ticket, :foreign_key => :tick_tt, :primary_key => :tt_id
  belongs_to :funcion, :foreign_key => :tick_fun, :primary_key => :fun_id
  belongs_to :est_tick, :foreign_key => :tick_et, :primary_key => :et_id

  validates :tick_id , uniqueness: true
end

app/models/tipo_sala.rb
class TipoSala < ApplicationRecord
  has_many :sala, :foreign_key => :sala_ts, :primary_key => :ts_id

  validates :ts_id , uniqueness: true
end

app/models/tipo_ticket.rb
class TipoTicket < ApplicationRecord
  has_many :ticket, :foreign_key => :tick_tt, :primary_key => :tt_id

  validates :tt_id , uniqueness: true
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :cargo, :foreign_key => :tra_car, :primary_key => :car_id
  belongs_to :cine, :foreign_key => :tra_cine, :primary_key => :cine_id

  has_one :admin, :foreign_key => :admin_id, :primary_key => :trabajador_rut

  validates :tra_id , uniqueness: true
end

app/models/v_tick_peli.rb
class VTickPeli < ApplicationRecord
end

app/controllers/est_funs_controller.rb
class EstFunsController < ApplicationController
  before_action :set_est_fun, only: [:show, :edit, :update, :destroy]

  # GET /est_funs
  def index
    @est_funs = EstFun.all
  end

  # GET /est_funs/1
  def show
  end

  # GET /est_funs/new
  def new
    @est_fun = EstFun.new
  end

  # GET /est_funs/1/edit
  def edit
  end

  # POST /est_funs
  def create
    @est_fun = EstFun.new(est_fun_params)

    if @est_fun.save
      redirect_to @est_fun, notice: 'Est fun ha sido agregado exitosamente.'
    else
      redirect_to page_mtb_path, notice: 'Est fun no se pudo agregar.'
    end
  end

  # PATCH/PUT /est_funs/1
  def update
    if @est_fun.update(est_fun_params)
      redirect_to @est_fun, notice: 'Est fun ha sido actualizado.'
    else
      redirect_to page_mtb_path, notice: 'Est fun no se pudo actualizar.'
    end
  end

  # DELETE /est_funs/1
  def destroy
    @est_fun.destroy
    redirect_to page_mtb_path, notice: 'Est fun ha sido eliminado.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_est_fun
      @est_fun = EstFun.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def est_fun_params
      params.require(:est_fun).permit(:ef_id, :ef_desc)
    end
end

app/helpers/cines_helper.rb
module CinesHelper
end

app/helpers/est_funs_helper.rb
module EstFunsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/est_funs/_form.html.erb
<%= form_with(model: est_fun, local: true, class: "form-horizontal") do |form| %>
  <% if est_fun.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(est_fun.errors.count, "error") %> prohibited this est_fun from being saved:</h2>

      <ul>
      <% est_fun.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= form.label :ef_id, "ID" , class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= form.text_field :ef_id, id: :est_fun_ef_id, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= form.label :ef_desc , "Descripcion" , class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= form.text_field :ef_desc, id: :est_fun_ef_desc, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-9 col-sm-offset-3">
    <div class="actions">
      <%= form.submit "Enviar", class: "btn btn-block btn-success "%>
    </div>
  </div>
</div>
<% end %>

</form>

app/views/est_funs/edit.html.erb
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Editar Estado Funcion</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render 'form', est_fun: @est_fun %>

          <%= link_to '<i class="fa fa-backward"></i> Back'.html_safe, page_mtb_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/est_funs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Est Funs</h1>

<table>
  <thead>
    <tr>
      <th>Ef desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @est_funs.each do |est_fun| %>
      <tr>
        <td><%= est_fun.ef_desc %></td>
        <td><%= link_to 'Show', est_fun %></td>
        <td><%= link_to 'Edit', edit_est_fun_path(est_fun) %></td>
        <td><%= link_to 'Destroy', est_fun, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Est Fun', new_est_fun_path %>

app/views/est_funs/new.html.erb
<h1>New Est Fun</h1>

<%= render 'form', est_fun: @est_fun %>

<%= link_to 'Back', est_funs_path %>

app/views/est_funs/show.html.erb
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Detalles Estado Funcion</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <dl class="dl-horizontal">
            <dt>ID</dt>
            <dd><%= @est_fun.ef_id %></dd>
            <dt>Descripcion</dt>
            <dd><%= @est_fun.ef_desc %></dd>
          </dl>
        </div>
      </div>
      <%= link_to '<i class="fa fa-pencil"></i> Editar'.html_safe, edit_est_fun_path(@est_fun), class: "btn btn-warning" %>
      <%= link_to '<i class="fa fa-backward"></i> Volver'.html_safe,page_mtb_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>