config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :tickets
  resources :funcions
  resources :salas
  resources :trabajadors
  resources :pais_origens
  resources :cines
  resources :est_ticks
  resources :est_funs
  resources :horarios
  resources :tipo_tickets
  resources :tipo_salas
  resources :cargos
  resources :edads
  resources :peliculas
  resources :generos
  resources :pruebas

  get 'page/index'
  get 'page/vista'
  get 'page/procedimiento'
  get 'page/auditor'
  get 'page/mtb'
  get 'pages/index'
  get 'pages/vista'
  get 'pages/procedimiento'
  get 'pages/auditor'
  get 'pages/mtb'

  root 'page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :trabajador, :foreign_key => :admin_id, :primary_key => :trabajador_rut
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auditor.rb
class Auditor < ApplicationRecord
  self.table_name = "audit_tables"
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  #self.primary_key = :car_id
  has_many :trabajador, :foreign_key => :tra_car, :primary_key => :car_id

  validates :car_id , uniqueness: true
end

app/models/cine.rb
class Cine < ApplicationRecord
  has_many :trabajador, :foreign_key => :tra_cine, :primary_key => :cine_id
  has_many :sala, :foreign_key => :sala_cine, :primary_key => :cine_id

  validates :cine_id , uniqueness: true
end

app/models/edad.rb
class Edad < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_ed, :primary_key => :ed_id

  validates :ed_id , uniqueness: true
end

app/models/est_fun.rb
class EstFun < ApplicationRecord
  has_many :funcion, :foreign_key => :fun_ef, :primary_key => :ef_id

  validates :ef_id , uniqueness: true
end

app/models/est_tick.rb
class EstTick < ApplicationRecord
  has_many :ticket, :foreign_key => :tick_et, :primary_key => :et_id

  validates :et_id , uniqueness: true
end

app/models/funcion.rb
class Funcion < ApplicationRecord
  belongs_to :sala, :foreign_key => :fun_sala, :primary_key => :sala_id
  belongs_to :est_fun, :foreign_key => :fun_ef, :primary_key => :ef_id
  belongs_to :pelicula, :foreign_key => :fun_peli, :primary_key => :peli_id
  belongs_to :horario, :foreign_key => :fun_hor, :primary_key => :hor_id
  has_many :ticket, :foreign_key => :tick_fun, :primary_key => :fun_id

  validates :fun_id , uniqueness: true
end

app/models/genero.rb
class Genero < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_gen, :primary_key => :gen_id

  validates :gen_id , uniqueness: true
end

app/models/horario.rb
class Horario < ApplicationRecord
  has_many :funcion, :foreign_key => :fun_hor, :primary_key => :hor_id

  validates :hor_id , uniqueness: true
end

app/models/pais_origen.rb
class PaisOrigen < ApplicationRecord
  has_many :pelicula, :foreign_key => :peli_po, :primary_key => :po_id

  validates :po_id , uniqueness: true
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
  belongs_to :edad, :foreign_key => :peli_ed, :primary_key => :ed_id
  belongs_to :genero, :foreign_key => :peli_gen, :primary_key => :gen_id
  belongs_to :pais_origen, :foreign_key => :peli_po, :primary_key => :po_id
  has_many :funcion, :foreign_key => :fun_peli, :primary_key => :peli_id

  validates :peli_id , uniqueness: true
end

app/models/prueba.rb
class Prueba < ApplicationRecord
end

app/models/sala.rb
class Sala < ApplicationRecord
  belongs_to :tipo_sala, :foreign_key => :sala_ts, :primary_key => :ts_id
  belongs_to :cine, :foreign_key => :sala_cine, :primary_key => :cine_id
  has_many :funcion, :foreign_key => :fun_sala, :primary_key => :sala_id

  validates :sala_id , uniqueness: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :tipo_ticket, :foreign_key => :tick_tt, :primary_key => :tt_id
  belongs_to :funcion, :foreign_key => :tick_fun, :primary_key => :fun_id
  belongs_to :est_tick, :foreign_key => :tick_et, :primary_key => :et_id

  validates :tick_id , uniqueness: true
end

app/models/tipo_sala.rb
class TipoSala < ApplicationRecord
  has_many :sala, :foreign_key => :sala_ts, :primary_key => :ts_id

  validates :ts_id , uniqueness: true
end

app/models/tipo_ticket.rb
class TipoTicket < ApplicationRecord
  has_many :ticket, :foreign_key => :tick_tt, :primary_key => :tt_id

  validates :tt_id , uniqueness: true
end

app/models/trabajador.rb
class Trabajador < ApplicationRecord
  belongs_to :cargo, :foreign_key => :tra_car, :primary_key => :car_id
  belongs_to :cine, :foreign_key => :tra_cine, :primary_key => :cine_id

  has_one :admin, :foreign_key => :admin_id, :primary_key => :trabajador_rut

  validates :tra_id , uniqueness: true
end

app/models/v_tick_peli.rb
class VTickPeli < ApplicationRecord
end

app/controllers/tipo_salas_controller.rb
class TipoSalasController < ApplicationController
  before_action :set_tipo_sala, only: [:show, :edit, :update, :destroy]

  # GET /tipo_salas
  def index
    @tipo_salas = TipoSala.all
  end

  # GET /tipo_salas/1
  def show
  end

  # GET /tipo_salas/new
  def new
    @tipo_sala = TipoSala.new
  end

  # GET /tipo_salas/1/edit
  def edit
  end

  # POST /tipo_salas
  def create
    @tipo_sala = TipoSala.new(tipo_sala_params)

    if @tipo_sala.save
      redirect_to @tipo_sala, notice: 'Tipo sala ha sido agregado exitosamente.'
    else
      redirect_to page_mtb_path, notice: 'Tipo sala no se pudo agregar.'
    end
  end

  # PATCH/PUT /tipo_salas/1
  def update
    if @tipo_sala.update(tipo_sala_params)
      redirect_to @tipo_sala, notice: 'Tipo sala ha sido actualizado.'
    else
      redirect_to page_mtb_path, notice: 'Tipo sala no se pudo agregar.'
    end
  end

  # DELETE /tipo_salas/1
  def destroy
    @tipo_sala.destroy
    redirect_to page_mtb_path, notice: 'Tipo sala ha sido eliminado.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_sala
      @tipo_sala = TipoSala.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tipo_sala_params
      params.require(:tipo_sala).permit(:ts_id, :ts_desc)
    end
end

app/helpers/cines_helper.rb
module CinesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/tipo_salas_helper.rb
module TipoSalasHelper
end

app/views/tipo_salas/_form.html.erb
<%= form_with(model: tipo_sala, local: true, class: "form-horizontal") do |form| %>
  <% if tipo_sala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_sala.errors.count, "error") %> prohibited this tipo_sala from being saved:</h2>

      <ul>
      <% tipo_sala.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :ts_id, "ID" , class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= form.text_field :ts_id, id: :tipo_sala_ts_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :ts_desc , "Descripcion" , class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= form.text_field :ts_desc, id: :tipo_sala_ts_desc, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <div class="actions">
        <%= form.submit "Enviar", class: "btn btn-block btn-success "%>
      </div>
    </div>
  </div>
  <% end %>
</form>

app/views/tipo_salas/edit.html.erb
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Editar Tipo Sala</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render 'form', tipo_sala: @tipo_sala %>

          <%= link_to '<i class="fa fa-backward"></i> Back'.html_safe, page_mtb_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tipo_salas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Salas</h1>

<table>
  <thead>
    <tr>
      <th>Ts desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_salas.each do |tipo_sala| %>
      <tr>
        <td><%= tipo_sala.ts_desc %></td>
        <td><%= link_to 'Show', tipo_sala %></td>
        <td><%= link_to 'Edit', edit_tipo_sala_path(tipo_sala) %></td>
        <td><%= link_to 'Destroy', tipo_sala, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Sala', new_tipo_sala_path %>

app/views/tipo_salas/new.html.erb
<h1>New Tipo Sala</h1>

<%= render 'form', tipo_sala: @tipo_sala %>

<%= link_to 'Back', tipo_salas_path %>

app/views/tipo_salas/show.html.erb
  <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Detalles Tipo Sala</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <dl class="dl-horizontal">
            <dt>ID</dt>
            <dd><%= @tipo_sala.ts_id %></dd>
            <dt>Descripcion</dt>
            <dd><%= @tipo_sala.ts_desc %></dd>
          </dl>
        </div>
      </div>
      <%= link_to '<i class="fa fa-pencil"></i> Editar'.html_safe, edit_tipo_sala_path(@tipo_sala), class: "btn btn-warning" %>
      <%= link_to '<i class="fa fa-backward"></i> Volver'.html_safe,page_mtb_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>